### PR TITLE
Validate that input accountID matches the current aws context

### PR DESCRIPTION
**Pull request by haresh-suresh**
…ontext when running TF

### CODE REVIEW

**Review by cgeers — CHANGES_REQUESTED** [review]
I don't think this is correct approach. I thought we'd be using [the builtin functionality](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#allowed_account_ids) for this and keep the change tiny and in the snippet only, precisely so we didn't have to make this change.

Is there some reason why this simpler builtin functionality is insufficient in some way?

**Comment by haresh-suresh** [comment]
> I don't think this is correct approach. I thought we'd be using [the builtin functionality](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#allowed_account_ids) for this and keep the change tiny and in the snippet only, precisely so we didn't have to make this change.
> 
> Is there some reason why this simpler builtin functionality is insufficient in some way?

I liked the custom error message of this approach, that's all it was.

**Comment by nkraemer-sysdig** [comment]
Yeah FWIW I always assumed this would look more like Azure where we add `subscription_id` as a field in the provider itself. I think the param chris linked is more in line with what I was expecting

**Comment by haresh-suresh** [comment]
Sounds good, I will close this and just update the examples and test 👍

**Pull request closed without merging**
